on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  merge_group:
    types: [checks_requested]
permissions: read-all
name: Integration
jobs:
  alpine-linux:
    name: Run on Alpine Linux
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: apk add --no-cache musl-dev build-base
      - name: Build rv
        run: cargo build --release
      - name: Test rv works
        run: |
          ./target/release/rv --version
          ./target/release/rv --help

  arch-linux:
    name: Run on Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: pacman -Syu --noconfirm base-devel rustup
      - name: Install Rust toolchain
        run: rustup default stable
      - name: Build rv
        run: cargo build --release
      - name: Test rv works
        run: |
          ./target/release/rv --version
          ./target/release/rv --help
