name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest # x86
          - macos-latest # xarm
          - ubuntu-24.04-arm #arm
          - macos-15-intel # x86

    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Install additional shells
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y zsh fish
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - run: ./bin/test

  run-tests-coverage:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spinel-coop/rv' }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Install additional shells
        run: sudo apt-get update && sudo apt-get install -y zsh fish
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests with coverage
        shell: bash
        run: ./bin/test-cov
        env:
          RUST_BACKTRACE: 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: spinel-coop/rv
          fail_ci_if_error: true
          flags: unittests
          verbose: true
          files: lcov.info
